name: stream_feed
description: Stream Feed unofficial Dart SDK.
  Dart and Flutter.
version: 0.6.0+2
repository: https://github.com/winnee0solta/stream-feed-flutter-unofficial
issue_tracker: https://github.com/winnee0solta/stream-feed-flutter-unofficial/issues
homepage: https://github.com/winnee0solta/stream-feed-flutter-unofficial
environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  dio: ^4.0.6
  equatable: ^2.0.0
  faye_dart: ^0.1.1+2
  http_parser: ^4.0.0
  intl: ^0.19.0
  jose: ^0.3.2
  json_annotation: ^4.4.0
  logging: ^1.0.1
  meta: ^1.3.0
  mime: ^1.0.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  test: ^1.17.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
